# Name of your site (displayed in the header)
name: John Kim

# Short bio or description (displayed in the header)
description: Some words, mostly pictures

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/avatar.jpg

# Tabs in header.
navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# Includes an icon in the footer for each username you enter
footer-links:
  behance:
  dribbble:
  email: hk3yz@virginia.edu
  facebook:
  flickr:
  github:
  googleplus:
  instagram: johnkimthehuman
  linkedin:
  pinterest:
  rss:
  stackoverflow:
  tumblr:
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: © 2024 John Kim

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # <username>.disqus.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

excerpt_separator: <!--more-->

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: pretty

pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate-v2

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
